name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key

          ssh -i deploy_key -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'pm2 stop hawbot'
          scp -i deploy_key -o StrictHostKeyChecking=no -r ./app/* ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/root/deployments/hawbot
          scp -i deploy_key -o StrictHostKeyChecking=no -r ./node_modules ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/root/deployments/hawbot
          ssh -i deploy_key -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'pm2 start hawbot'
